version: "3.9"

services:
  backend:
    build: ../backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - PORT=8000
    restart: unless-stopped

  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
